"use strict";
Atlas.registerPlate({
  id: "hyper",
  name: "The Hyperbolic Plane",
  roman: "XLVII",
  accent: "#90b8f0",
  tex: "\\{p,q\\}:\\;(p\\!-\\!2)(q\\!-\\!2)>4,\\qquad z\\mapsto\\bar z,\\quad e^{2\\pi i/p}\\,\\bar z,\\quad c+\\dfrac{r^{2}(z-c)}{|z-c|^{2}}",
  plain: "{p,q}: (p−2)(q−2) > 4;   mirrors z ↦ z̄,  e^(2πi/p)·z̄,  c + r²(z−c)/|z−c|²",
  caption: "The plane of Bolyai and Lobachevsky, tiled by regular P-gons meeting Q to a vertex — hyperbolic exactly when (p−2)(q−2) > 4. Each point is born on one edge of the fundamental polygon and pushed through a random word of the three generating mirrors, WORD LENGTH reflections deep; COLOR tints the generations into rings. The crowding at the rim is not perspective: the disk keeps angles true but compresses area, and hyperbolic circles grow exponentially with radius, so congruent tiles must pile against the boundary — the brightness gradient is the metric itself, the crowding Escher drew in Circle Limit from Coxeter's figure. MODEL lifts the disk onto the hyperboloid model.",
  cam: { dist: 2.9, pitch: 0.55, tgtY: 0.0, rot: 0.03 },
  gain: 0.85,
  params: [
    { label: "P",           min: 3, max: 8,  step: 1,    def: 5    },
    { label: "Q",           min: 3, max: 8,  step: 1,    def: 4    },
    { label: "WORD LENGTH", min: 2, max: 24, step: 1,    def: 12   },
    { label: "MODEL",       min: 0, max: 1,  step: 0.01, def: 0.0  },
    { label: "COLOR",       min: 0, max: 1,  step: 0.01, def: 0.55 },
    { label: "GLOW",        min: 0, max: 1,  step: 0.01, def: 0.6  }
  ],
  glsl: `
vec3 shape_hyper(vec2 q, vec4 rnd, uint seed, float P[8], out vec3 col){
  /* {p,q} tiling of the Poincare disk, generated by its mirror group */
  int np = int(P[0] + 0.5); np = max(3, min(8, np));
  int nq = int(P[1] + 0.5); nq = max(3, min(8, nq));
  float sp = sin(PI/float(np));
  float cq = cos(PI/float(nq));
  for(int i = 0; i < 8; i++){       /* spherical/Euclidean combo: raise q until hyperbolic */
    if(cq*cq - sp*sp > 1.0e-4) break;
    nq += 1;
    cq = cos(PI/float(nq));
  }
  float root = sqrt(max(cq*cq - sp*sp, 1.0e-6));
  float d = cq/root;                /* mirror-arc center; d*d - r*r = 1 exactly, */
  float r = sp/root;                /* so the arc meets the unit circle at right angles */
  vec2  c = vec2(d, 0.0);
  float wedge = PI/float(np);

  /* draw from the polygon edge: the sub-arc between the two vertices,
     found where the wedge boundary line at angle pi/p cuts the circle */
  float cw = cos(wedge);
  float tv = d*cw - sqrt(max(d*d*cw*cw - 1.0, 0.0));   /* vertex radius */
  float cpsiv = clamp((d - tv*cw)/max(r, 1.0e-9), -1.0, 1.0);
  float psiv = acos(cpsiv);
  float psi = (q.x - 0.5)*2.0*psiv;
  vec2 z = c - r*vec2(cos(psi), sin(psi));
  if(abs(atan(z.y, z.x)) > wedge || dot(z, z) >= 1.0){ /* numerical guard */
    col = vec3(0.0);
    return vec3(0.0, -999.0, 0.0);
  }

  /* random word in the three mirrors, never repeating the last one */
  int wlen = int(P[2] + 0.5); wlen = max(2, min(24, wlen));
  int klen = int(rnd.w*float(wlen));                   /* 0 .. wlen-1 generations */
  uint h = seed;
  int lastM = 0;
  vec2 R = vec2(cos(TAU/float(np)), sin(TAU/float(np)));
  for(int j = 0; j < 24; j++){
    if(j >= klen) break;
    h = hashu(h);
    int m = 0;
    if(lastM == 0){ m = 1 + int(u2f(h)*2.99999); }
    else if(lastM == 1){ m = ((h & 1u) == 0u) ? 2 : 3; }
    else if(lastM == 2){ m = ((h & 1u) == 0u) ? 1 : 3; }
    else               { m = ((h & 1u) == 0u) ? 1 : 2; }
    if(m == 1){ z = vec2(z.x, -z.y); }                 /* reflect in the x-axis */
    else if(m == 2){ z = cmul(R, vec2(z.x, -z.y)); }   /* reflect in the line at pi/p */
    else{                                              /* invert in the edge arc */
      vec2 wv = z - c;
      z = c + r*r*wv/(dot(wv, wv) + 1.0e-9);
    }
    float zz = dot(z, z);
    if(zz > 0.998001){ z *= 0.999*inversesqrt(zz); }   /* float-drift clamp */
    lastM = m;
  }

  /* gentle intrinsic motion: a small Mobius automorphism of the disk is an
     isometry, so the whole tiling slides rigidly under it */
  vec2 aa = 0.05*vec2(cos(uT*0.10), sin(uT*0.073));
  z = cdiv(z + aa, vec2(1.0, 0.0) + cmul(vec2(aa.x, -aa.y), z));
  float zz2 = dot(z, z);
  if(zz2 > 0.998001){ z *= 0.999*inversesqrt(zz2); }

  /* disk model flat in xz  ->  hyperboloid lift */
  float mdl = clamp(P[3], 0.0, 1.0);
  float s2 = dot(z, z);
  if(mdl > 0.001 && s2 > 0.970225){  /* |z| > 0.985 lifts far outside the frame */
    col = vec3(0.0);
    return vec3(0.0, -999.0, 0.0);
  }
  vec3 diskP = vec3(z.x, 0.0, z.y)*1.2;
  float den = max(1.0 - s2, 1.0e-4);
  vec3 hypP = vec3(0.6*z.x/den, 0.3*(1.0 + s2)/den - 0.45, 0.6*z.y/den);
  vec3 pos = mix(diskP, hypP, mdl);

  col = pal(float(klen)/float(wlen)*0.85 + P[4],
            vec3(0.5), vec3(0.5), vec3(1.0), vec3(0.0, 0.33, 0.67));
  col *= 0.5 + 0.7*P[5];
  return pos;
}`
});
